---
title: "R Notebook"
output: html_notebook
---

## Load the function to be tested
```{r}
source("make.design.matrix.R")
```

## Load the input file
```{r}
scExpDesign <- readRDS("../data/single_cell_design_file.RDS")

head(scExpDesign)
colnames(scExpDesign) <- c("Time", "Replicate", "LinOne", "LinTwo")

meta.mtx <- readRDS("../data/metagene.mtx")
```

## Test output
```{r}
source("make.design.matrix.R")
exp.design.matrix <- make.design.matrix(scExpDesign, degree = 3, 
                                        repl.col = 2)
```

```{r}
source("p.vector.R")
library(MASS) 

metagene.mtx <-abs(meta.mtx)

fit <- p.vector(metagene.mtx, exp.design.matrix, Q = 0.05, MT.adjust = "BH", min.obs = 10, counts = T, family = negative.binomial(10))
```


```{r}
source("T.fit.R")
library(MASS) 


tstep <- T.fit(fit,
               design = fit$dis,
               step.method = "backward",
               alfa = fit$Q, min.obs = fit$min.obs,
               nvar.correction = F, item = "gene", family = fit$family)

```











































